"""Portable ParticleMonitor dynamic-aperture analysis and plotting.

Copy this file anywhere; PASS and its GUI are not required.
Dependencies: Python >= 3.11, NumPy, h5py, Matplotlib.
Generated by tools/export_dynamic_aperture.py; edit the source modules.
"""

from __future__ import annotations

from pathlib import Path
import csv
import io
import json
import shlex

import numpy as np

# PASS/utils/particle_monitor_read.py: 5e2fcd07881f9ab5573044b83cc066052b621af1db21041afabd937e40fcd798
# PASS/analysis/dynamic_aperture.py: ac47d1978872c0eff22b1c9ab2a7122734d4d69076e3d79cafaf3fd678817284
# PASS/plot/plot_dynamic_aperture.py: 52816816df33ced4455c13248a767f61eeb6d081e544a4a118b2c1e7028e164f

# Source: PASS/utils/particle_monitor_read.py


def _integer(value, name, minimum=0):
    if isinstance(value, (bool, np.bool_)) or not isinstance(value, (int, np.integer)) or value < minimum:
        raise ValueError(f"{name} must be an integer >= {minimum}")
    return int(value)


def _read_header(stream):
    attributes, names, types = {}, None, None
    while line := stream.readline():
        text = line.decode("utf-8-sig").strip()
        if not text or text.startswith(("#", "!")):
            continue
        fields = shlex.split(text)
        if fields[0] == "@" and len(fields) == 4:
            kind, value = fields[2:]
            attributes[fields[1]] = value if kind.endswith("s") else int(value) if kind.endswith("d") else float(value)
        elif fields[0] == "*":
            names = fields[1:]
        elif fields[0] == "$":
            types = fields[1:]
            break
        else:
            raise ValueError("Invalid ParticleMonitor TFS header")
    if not names or types is None or len(names) != len(types) or len(set(names)) != len(names):
        raise ValueError("ParticleMonitor TFS requires unique typed columns")
    return attributes, names, types, stream.tell()


def _inspect(stream):
    # Leave other TFS dialects to their existing reader.
    identifiers = {}
    while line := stream.readline():
        if line.lstrip().startswith(b"$"):
            break
        if line.lstrip().startswith(b"@"):
            fields = shlex.split(line.decode("utf-8-sig"))
            if len(fields) == 4 and fields[1] in {"Name", "Layout"}:
                identifiers[fields[1]] = fields[3]
    if identifiers.get("Name") != "PASS Particle Monitor" or identifiers.get("Layout") == "table":
        return None
    if identifiers.get("Layout") != "single_file":
        raise ValueError("ParticleMonitor requires the current single-file format")
    stream.seek(0)
    attributes, names, types, start = _read_header(stream)
    if attributes.get("FormatVersion") != 2:
        raise ValueError("Unsupported ParticleMonitor format; current format version is 2")
    required = {"record", "turn", "particle_id", "x", "px", "y", "py", "z", "dp", "tag", "lostTurn", "lostPosition"}
    if not required.issubset(names) or any(kind not in {"%d", "%le"} for kind in types):
        raise ValueError("ParticleMonitor TFS requires numeric trajectory and identity columns")
    for name in ("record", "turn", "particle_id", "tag", "lostTurn"):
        if types[names.index(name)] != "%d":
            raise ValueError(f"ParticleMonitor {name} must be an integer column")
    _integer(attributes.get("MaxTag"), "MaxTag", 1)
    for name in ("ValidSamples", "ValidRows", "NumTurn", "StartTurn", "EndTurn", "RequestedEndTurn"):
        _integer(attributes.get(name), name)
    if attributes["NumTurn"] != attributes["ValidSamples"]:
        raise ValueError("ParticleMonitor sample counts disagree")
    if attributes.get("Completed") not in (0, 1):
        raise ValueError("ParticleMonitor Completed must be 0 or 1")
    attributes["Completed"] = bool(attributes["Completed"])
    return attributes, names, types, start


def particle_monitor_tfs_metadata(path):
    """Return current PM metadata, or None for an ordinary TFS table."""
    with Path(path).open("rb") as stream:
        description = _inspect(stream)
    return description[0] if description is not None else None


def iter_particle_monitor_tfs(path, *, block_rows=65536, cancel=None):
    """Yield bounded numeric row blocks and validate the complete TFS table.

    Initial rows precede the turn-major sample rows. The iterator must be
    exhausted to verify the final row/sample counts.
    """
    block_rows = _integer(block_rows, "block_rows", 1)
    with Path(path).open("rb") as stream:
        description = _inspect(stream)
        if description is None:
            raise ValueError("Not a current ParticleMonitor TFS")
        attributes, names, types, start = description
        n_particles = attributes["MaxTag"]
        dtype = [(name, np.int64 if kind == "%d" else np.float64) for name, kind in zip(names, types)]
        n_rows, n_samples, last_initial_id, previous_turn = 0, 0, 0, -1
        stream.seek(start)
        while True:
            rows = []
            while len(rows) < block_rows and (line := stream.readline()):
                text = line.strip()
                if text.startswith(b"# PASS_PM_COMMIT"):
                    raise ValueError("ParticleMonitor TFS must be a finalized standard table")
                if text and not text.startswith((b"#", b"!")):
                    rows.append(line)
            if not rows:
                break
            if cancel is not None and cancel():
                raise InterruptedError("ParticleMonitor reading cancelled")
            array = np.loadtxt(io.BytesIO(b"".join(rows)), dtype=dtype, ndmin=1)
            values = {name: array[name] for name in names}
            record, turn, particle_id = (values[name] for name in ("record", "turn", "particle_id"))
            if np.any((record != 0) & (record != 1)) or np.any(turn < 0) or np.any((particle_id < 1) | (particle_id > n_particles)):
                raise ValueError("Invalid ParticleMonitor record, turn or particle identity")
            initial = record == 0
            initial_ids = particle_id[initial]
            if len(initial_ids):
                if n_samples or initial_ids[0] <= last_initial_id or np.any(np.diff(initial_ids) <= 0) or np.any(np.diff(record) < 0):
                    raise ValueError("Initial ParticleMonitor rows must precede samples in particle-ID order")
                if np.any(values["tag"][initial] != initial_ids):
                    raise ValueError("Initial ParticleMonitor rows require positive particle tags")
                last_initial_id = int(initial_ids[-1])
            selected = ~initial
            sample_ids, sample_turns = particle_id[selected], turn[selected]
            if len(sample_ids):
                positions = n_samples + np.arange(len(sample_ids), dtype=np.int64)
                if np.any(sample_ids != positions % n_particles + 1):
                    raise ValueError("ParticleMonitor samples must contain every particle ID in order")
                differences = np.diff(np.r_[previous_turn, sample_turns])
                starts = positions % n_particles == 0
                if np.any(differences[starts] <= 0) or np.any(differences[~starts] != 0):
                    raise ValueError("ParticleMonitor samples have inconsistent or non-increasing turns")
                tags = values["tag"][selected]
                if np.any((tags != 0) & (np.abs(tags) != sample_ids)):
                    raise ValueError("ParticleMonitor sample tags disagree with particle IDs")
                previous_turn = int(sample_turns[-1])
                n_samples += len(sample_ids)
            n_rows += len(array)
            yield values
        if n_samples != attributes["ValidSamples"] * n_particles or n_rows != attributes["ValidRows"]:
            raise ValueError("ParticleMonitor data do not cover the declared row and sample counts")
        if n_samples and attributes["EndTurn"] != previous_turn + 1:
            raise ValueError("ParticleMonitor EndTurn disagrees with its samples")
        if cancel is not None and cancel():
            raise InterruptedError("ParticleMonitor reading cancelled")


def read_particle_monitor_tfs(path, *, requested_turn=None, last_sample_only=False, cancel=None):
    """Read all rows, or initial rows plus the latest requested sample."""
    if requested_turn is not None:
        requested_turn = _integer(requested_turn, "requested_turn")
    attributes = particle_monitor_tfs_metadata(path)
    if attributes is None:
        raise ValueError("Not a current ParticleMonitor TFS")
    initial_parts, sample_parts, selected_turn = [], [], -1
    for block in iter_particle_monitor_tfs(path, cancel=cancel):
        initial = block["record"] == 0
        if np.any(initial):
            initial_parts.append({name: values[initial] for name, values in block.items()})
        selected = block["record"] == 1
        if last_sample_only:
            if requested_turn is not None:
                selected &= block["turn"] <= requested_turn
            if not np.any(selected):
                continue
            turn = int(block["turn"][selected][-1])
            if turn > selected_turn:
                sample_parts = []
                selected_turn = turn
            selected &= block["turn"] == selected_turn
        if np.any(selected):
            sample_parts.append({name: values[selected] for name, values in block.items()})
    parts = initial_parts + sample_parts
    if parts:
        columns = {name: np.concatenate([part[name] for part in parts]) for name in parts[0]}
    else:
        with Path(path).open("rb") as stream:
            _, names, types, _ = _read_header(stream)
        columns = {name: np.empty(0, dtype=np.int64 if kind == "%d" else np.float64) for name, kind in zip(names, types)}
    return columns, attributes


def read_particle_trajectories(path, *, max_tag=None):
    """Return particle-ID keyed trajectories from one current PM file."""
    if max_tag is not None:
        max_tag = _integer(max_tag, "max_tag", 1)
    if isinstance(path, (list, tuple)):
        if len(path) != 1:
            raise ValueError("Select exactly one ParticleMonitor file")
        path = path[0]
    path = Path(path)
    if path.suffix.lower() in {".h5", ".hdf5"}:
        import h5py

        with h5py.File(path, "r") as stream:
            if (stream.attrs.get("Name") != "PASS Particle Monitor" or stream.attrs.get("Layout") != "single_file"
                    or stream.attrs.get("FormatVersion") != 2):
                raise ValueError("ParticleMonitor requires the current single-file format version 2")
            count = _integer(stream.attrs.get("ValidSamples"), "ValidSamples")
            ids = stream["particle_id"][:]
            if ids.ndim != 1 or ids.dtype.kind not in "iu" or np.any(ids <= 0) or len(np.unique(ids)) != len(ids):
                raise ValueError("ParticleMonitor requires unique positive integer particle IDs")
            if stream["turn"].ndim != 1 or len(stream["turn"]) < count:
                raise ValueError("ParticleMonitor turn data do not cover ValidSamples")
            turns = stream["turn"][:count]
            fields = {name: item for name, item in stream.items() if name not in {"particle_id", "turn"} and isinstance(item, h5py.Dataset)}
            if any(item.ndim != 2 or item.shape[0] < count or item.shape[1] != len(ids) for item in fields.values()):
                raise ValueError("ParticleMonitor datasets do not cover the sample/particle shape")
            return {
                int(particle_id): dict(turn=turns.copy(), **{
                    name: item[:count, index]
                    for name, item in fields.items()
                })
                for index, particle_id in enumerate(ids) if max_tag is None or particle_id <= max_tag
            }
    records, attributes = read_particle_monitor_tfs(path)
    selected = records["record"] == 1
    shape = (attributes["ValidSamples"], attributes["MaxTag"])
    columns = {name: values[selected].reshape(shape) for name, values in records.items() if name not in {"record", "particle_id"}}
    return {
        index + 1: {
            name: values[:, index]
            for name, values in columns.items()
        }
        for index in range(shape[1] if max_tag is None else min(shape[1], max_tag))
    }


# Source: PASS/analysis/dynamic_aperture.py


def _integer_values(value, name, *, minimum=None):
    """Accept exact numeric integers without truncating them."""
    values = np.asarray(value)
    if values.dtype.kind not in "iuf":
        raise ValueError(f"{name} must contain finite integers")
    if values.dtype.kind == "f":
        if (not np.all(np.isfinite(values)) or np.any(values != np.floor(values)) or np.any(values < -(2**63)) or np.any(values >= 2**63)):
            raise ValueError(f"{name} must contain finite int64 integers")
    elif values.dtype.kind == "u" and np.any(values > np.iinfo(np.int64).max):
        raise ValueError(f"{name} exceeds int64 capacity")
    values = values.astype(np.int64, copy=False)
    if minimum is not None and np.any(values < minimum):
        raise ValueError(f"{name} must be at least {minimum}")
    return values


def _integer_scalar(value, name, *, minimum=0):
    values = _integer_values(value, name, minimum=minimum)
    if values.ndim != 0:
        raise ValueError(f"{name} must be one integer")
    return int(values)


def compute_dynamic_aperture(initial_coordinates,
                             *,
                             particle_id=None,
                             tag,
                             coordinates=None,
                             sample_turn,
                             lost_turn=None,
                             lost_position=None,
                             injection_turn=None,
                             initial_valid=None,
                             requested_turn=None,
                             metadata=None):
    """Classify an x-y scan at an explicitly observed monitor event.

    Initial coordinates are ``(particles, 6)`` in x, px, y, py, z, dp order.
    Sample arrays are ``(samples, particles)``; coordinates append a six-axis.
    Positive/negative/zero tags denote live/lost/unavailable particles. IDs must
    already be aligned to the initial rows; signed tags are checked against them.
    ``requested_turn`` is an inclusive simulation turn at this monitor, not a
    number of completed revolutions. If omitted, the last supplied turn is used.

    Only the last sample at or before that turn is classified. A live particle
    without a sample on the requested turn is incomplete. Numerical validity is
    checked in that sample when coordinates are supplied; historical excursions
    are not inferred. Missing initial coordinates are unavailable. Loss times
    are absolute simulation turns, not particle ages. This does not add physics,
    track particles, fit an outer hull, or assume symmetry or a simply connected
    stable region. Initial dp groups remain unchanged by subsequent RF kicks.
    """
    initial = np.asarray(initial_coordinates, dtype=float)
    if initial.ndim != 2 or initial.shape[1] != 6:
        raise ValueError("initial_coordinates must have shape (particles, 6)")
    n_particles = len(initial)
    ids = np.arange(1, n_particles + 1, dtype=np.int64) if particle_id is None else np.asarray(particle_id)
    if ids.shape != (n_particles, ) or ids.dtype.kind not in "iu" or np.any(ids <= 0) or len(np.unique(ids)) != n_particles:
        raise ValueError("particle_id must contain one unique positive integer per initial row")
    ids = ids.astype(np.int64, copy=False)
    turns = np.asarray(sample_turn)
    if turns.ndim != 1 or turns.dtype.kind not in "iu" or np.any(turns < 0) or np.any(np.diff(turns) <= 0):
        raise ValueError("sample_turn must be strictly increasing nonnegative integers")
    tags = np.asarray(tag)
    if tags.shape != (len(turns), n_particles):
        raise ValueError("tag must have shape (samples, particles)")
    if not np.all(np.isfinite(tags)) or not np.all((tags == 0) | (np.abs(tags) == ids[None, :])):
        raise ValueError("nonzero signed tags must match the aligned particle_id")
    if requested_turn is None:
        requested_turn = int(turns[-1]) if len(turns) else 0
    if isinstance(requested_turn, (bool, np.bool_)) or not isinstance(requested_turn, (int, np.integer)) or requested_turn < 0:
        raise ValueError("requested_turn must be a nonnegative integer")
    requested_turn = int(requested_turn)

    def particle_array(value, default, dtype, name):
        array = np.full(n_particles, default, dtype=dtype) if value is None else np.asarray(value, dtype=dtype)
        if array.shape != (n_particles, ):
            raise ValueError(f"{name} must have shape (particles,)")
        return array

    valid = particle_array(initial_valid, True, bool, "initial_valid") & np.all(np.isfinite(initial), axis=1)
    born = particle_array(None if injection_turn is None else _integer_values(injection_turn, "injection_turn", minimum=-1), -1, np.int64,
                          "injection_turn")
    status = np.full(n_particles, "unavailable", dtype="<U12")
    observed = np.full(n_particles, -1, dtype=np.int64)
    loss = np.full(n_particles, -1, dtype=np.int64)
    position = np.full(n_particles, np.nan)
    last = np.full((n_particles, 6), np.nan)
    selected = np.searchsorted(turns, requested_turn, side="right") - 1

    def sample_array(value, name):
        if value is None:
            return None
        array = np.asarray(value)
        if array.shape != tags.shape:
            raise ValueError(f"{name} must have shape (samples, particles)")
        return array

    loss_samples = sample_array(lost_turn, "lost_turn")
    position_samples = sample_array(lost_position, "lost_position")
    if coordinates is not None:
        coordinates = np.asarray(coordinates)
        if coordinates.shape != tags.shape + (6, ):
            raise ValueError("coordinates must have shape (samples, particles, 6)")
    if selected >= 0:
        current = tags[selected]
        if np.any((current != 0) & (born > turns[selected])):
            raise ValueError("a recorded particle state cannot precede its injection turn")
        available = valid & (current != 0) & ((born < 0) | (born <= requested_turn))
        observed[available] = int(turns[selected])
        status[available] = "incomplete"
        live = available & (current > 0)
        if int(turns[selected]) == requested_turn:
            status[live] = "survived"
        dead = available & (current < 0)
        if loss_samples is not None:
            values = _integer_values(loss_samples[selected], "lost_turn", minimum=-1)
            known = dead & (values >= 0)
            loss[known] = values[known]
            if np.any(known & (loss > turns[selected])):
                raise ValueError("a recorded loss turn cannot be later than its sample")
            if np.any(known & (born >= 0) & (loss < born)):
                raise ValueError("a recorded loss turn cannot precede its injection turn")
        status[dead] = "lost"
        if position_samples is not None:
            position[dead] = position_samples[selected, dead]
        if coordinates is not None:
            last[:] = coordinates[selected]
            finite = np.all(np.isfinite(last), axis=1)
            # px and py are mechanical momenta normalized to reference momentum.
            with np.errstate(over="ignore", invalid="ignore"):
                momentum_ratio = 1.0 + last[:, 5]
                longitudinal_squared = momentum_ratio**2 - last[:, 1]**2 - last[:, 3]**2
            physical = finite & (momentum_ratio > 0) & np.isfinite(longitudinal_squared) & (longitudinal_squared > 0)
            status[available & ~physical] = "invalid"
    result_metadata = dict(metadata or {})
    result_metadata.update({
        "requested_turn": requested_turn,
        "sample_event": "at the selected monitor; turn labels do not establish completed revolutions",
        "coordinate_order": ["x", "px", "y", "py", "z", "dp"],
        "dp_grouping": "initial_coordinates[:, 5]",
        "validity_scope": "selected sample only" if coordinates is not None else "coordinates not checked",
    })
    return {
        "particle_id": ids,
        "initial_coordinates": initial.copy(),
        "initial_valid": valid,
        "injection_turn": born,
        "status": status,
        "observed_turn": observed,
        "lost_turn": loss,
        "lost_position": position,
        "final_coordinates": last,
        "dp_values": np.unique(initial[valid, 5]),
        "metadata": result_metadata,
    }


def _attributes(stream):
    return {
        key: value.decode("utf-8") if isinstance(value, bytes) else value.item() if isinstance(value, np.generic) else value
        for key, value in stream.attrs.items()
    }


def _check_cancel(cancel):
    if cancel is not None and cancel():
        raise InterruptedError("Dynamic-aperture reading cancelled")


def _read_single_file_tfs(path, requested_turn, cancel, clamp_to_available):

    columns, attrs = read_particle_monitor_tfs(path, requested_turn=requested_turn, last_sample_only=True, cancel=cancel)
    ids = np.arange(1, attrs["MaxTag"] + 1, dtype=np.int64)
    initial = np.full((len(ids), 6), np.nan)
    born = np.full(len(ids), -1, dtype=np.int64)
    valid = np.zeros(len(ids), dtype=bool)
    initial_rows = columns["record"] == 0
    initial_ids = columns["particle_id"][initial_rows]
    if np.any(columns["tag"][initial_rows] != initial_ids):
        raise ValueError("Initial ParticleMonitor records require their positive particle tag")
    coordinate_names = ("x", "px", "y", "py", "z", "dp")
    initial[initial_ids - 1] = np.column_stack([columns[name][initial_rows] for name in coordinate_names])
    born[initial_ids - 1] = columns["turn"][initial_rows]
    valid[initial_ids - 1] = True
    sample_rows = columns["record"] == 1
    turns = np.unique(columns["turn"][sample_rows])
    # The TFS reader validates every row even when it returns only an earlier sample.
    last_sample_turn = int(attrs["EndTurn"]) - 1 if attrs["ValidSamples"] > 0 else None
    target = _resolve_turn(requested_turn, attrs, turns, clamp_to_available=clamp_to_available, last_sample_turn=last_sample_turn)
    coordinates = np.column_stack([columns[name][sample_rows] for name in coordinate_names]).reshape(len(turns), len(ids), 6)
    return compute_dynamic_aperture(initial,
                                    particle_id=ids,
                                    tag=columns["tag"][sample_rows].reshape(len(turns), len(ids)),
                                    coordinates=coordinates,
                                    sample_turn=turns,
                                    lost_turn=columns["lostTurn"][sample_rows].reshape(len(turns), len(ids)),
                                    lost_position=columns["lostPosition"][sample_rows].reshape(len(turns), len(ids)),
                                    injection_turn=born,
                                    initial_valid=valid,
                                    requested_turn=target,
                                    metadata={
                                        **attrs, "sources": [str(path)],
                                        "initial_source": "injection capture",
                                        "last_sample_turn": last_sample_turn,
                                        "requested_turn_input": requested_turn
                                    })


def read_dynamic_aperture(path, *, requested_turn=None, cancel=None, clamp_to_available=False):
    """Read one current ParticleMonitor file without loading its full history.

    Injection coordinates are taken from the monitor's initial records. The
    default horizon is RequestedEndTurn-1; requested_turn is an inclusive
    simulation turn at the monitor location. With ``clamp_to_available=True``,
    an explicit turn beyond the last committed sample is reduced to that sample's
    turn. Automatic horizons and unsampled gaps are never clamped; they retain
    incomplete-state detection. Empty histories remain unavailable. Metadata
    reports ``requested_turn_input``, the effective ``requested_turn``, and
    ``last_sample_turn`` (None for an empty history).
    """
    import h5py

    path = Path(path)
    if not path.is_file():
        raise ValueError("Select one ParticleMonitor file")
    _check_cancel(cancel)
    if not isinstance(clamp_to_available, (bool, np.bool_)):
        raise ValueError("clamp_to_available must be a boolean")
    if requested_turn is not None:
        requested_turn = _resolve_turn(requested_turn, {}, np.empty(0, dtype=np.int64))
    if path.suffix.lower() == ".tfs":
        return _read_single_file_tfs(path, requested_turn, cancel, clamp_to_available)
    if path.suffix.lower() not in {".h5", ".hdf5"}:
        raise ValueError("ParticleMonitor analysis supports HDF5 or TFS")
    with h5py.File(path, "r") as stream:
        attrs = _attributes(stream)
        if attrs.get("Name") != "PASS Particle Monitor" or attrs.get("Layout") != "single_file" or attrs.get("FormatVersion") != 2:
            raise ValueError("ParticleMonitor requires the current single-file format version 2")
        if "initial" not in stream:
            raise ValueError("ParticleMonitor has no injection initial coordinates")
        ids = stream["particle_id"][:]
        group = stream["initial"]
        if not np.array_equal(ids, group["particle_id"][:]):
            raise ValueError("ParticleMonitor initial IDs do not match its trajectory columns")
        initial = np.column_stack([group[name][:] for name in ("x", "px", "y", "py", "z", "dp")])
        born = group["injection_turn"][:]
        valid = group["valid"][:]
        count = _integer_scalar(attrs["ValidSamples"], "ValidSamples")
        if stream["turn"].ndim != 1 or count > len(stream["turn"]):
            raise ValueError("ParticleMonitor turn data must be one-dimensional and cover ValidSamples")
        for name in ("x", "px", "y", "py", "z", "dp", "tag", "lostTurn", "lostPosition"):
            dataset = stream[name]
            if dataset.ndim != 2 or dataset.shape[0] < count or dataset.shape[1] != len(ids):
                raise ValueError(f"ParticleMonitor {name} does not cover ValidSamples and particle IDs")
        turns = _integer_values(stream["turn"][:count], "sample turn", minimum=0)
        if np.any(np.diff(turns) <= 0):
            raise ValueError("Recorded sample turns must be strictly increasing")
        last_sample_turn = int(turns[-1]) if len(turns) else None
        target = _resolve_turn(requested_turn, attrs, turns, clamp_to_available=clamp_to_available, last_sample_turn=last_sample_turn)
        index = int(np.searchsorted(turns, target, side="right") - 1)
        rows = slice(index, index + 1) if index >= 0 else slice(0, 0)
        coordinates = np.stack([stream[name][rows] for name in ("x", "px", "y", "py", "z", "dp")], axis=-1)
        result = compute_dynamic_aperture(initial,
                                          particle_id=ids,
                                          tag=stream["tag"][rows],
                                          coordinates=coordinates,
                                          sample_turn=turns[rows],
                                          lost_turn=stream["lostTurn"][rows],
                                          lost_position=stream["lostPosition"][rows],
                                          injection_turn=born,
                                          initial_valid=valid,
                                          requested_turn=target,
                                          metadata={
                                              **attrs, "sources": [str(path)],
                                              "initial_source": "injection capture",
                                              "last_sample_turn": last_sample_turn,
                                              "requested_turn_input": requested_turn
                                          })
    _check_cancel(cancel)
    return result


def _resolve_turn(requested_turn, attrs, turns, *, clamp_to_available=False, last_sample_turn=None):
    if requested_turn is not None:
        if isinstance(requested_turn, bool) or not isinstance(requested_turn, (int, np.integer)) or requested_turn < 0:
            raise ValueError("requested_turn must be a nonnegative integer")
        return min(int(requested_turn), last_sample_turn) if clamp_to_available and last_sample_turn is not None else int(requested_turn)
    end = attrs.get("RequestedEndTurn", attrs.get("EndTurn"))
    if end is not None:
        end = _integer_scalar(end, "monitor EndTurn")
        if end > 0:
            return end - 1
    return _integer_scalar(turns[-1], "sample turn") if len(turns) else 0


def export_dynamic_aperture(result, path):
    """Export numeric points and metadata to NPZ, or CSV plus a JSON sidecar."""
    path = Path(path)
    metadata = json.dumps(result["metadata"],
                          ensure_ascii=False,
                          indent=2,
                          default=lambda value: value.tolist() if isinstance(value, np.ndarray) else str(value))
    if path.suffix.lower() == ".npz":
        np.savez(path, **{key: value for key, value in result.items() if key != "metadata"}, metadata_json=np.array(metadata))
    elif path.suffix.lower() == ".csv":
        names = ("particle_id", "x0", "px0", "y0", "py0", "z0", "dp0", "initial_valid", "injection_turn", "status", "observed_turn", "lost_turn",
                 "lost_position")
        with path.open("w", newline="", encoding="utf-8") as stream:
            writer = csv.writer(stream)
            writer.writerow(names)
            for index, particle_id in enumerate(result["particle_id"]):
                writer.writerow([
                    particle_id, *result["initial_coordinates"][index], result["initial_valid"][index], result["injection_turn"][index],
                    result["status"][index], result["observed_turn"][index], result["lost_turn"][index], result["lost_position"][index]
                ])
        path.with_suffix(".json").write_text(metadata, encoding="utf-8")
    else:
        raise ValueError("DA exports require .npz or .csv")
    return path


# Source: PASS/plot/plot_dynamic_aperture.py


def _draw_boundary(ax, x, y, status, fixed_coordinates, *, color="#273449", linestyle="--", label="Sampled aperture boundary", overlay=False):
    """Draw only transitions supported by fully classified Cartesian cells."""
    if not np.all(fixed_coordinates == fixed_coordinates[:1]):
        return False, "Boundary unavailable: px, py and z must be fixed within the dp group"
    unique_x, x_index = np.unique(x, return_inverse=True)
    unique_y, y_index = np.unique(y, return_inverse=True)
    cells = y_index * len(unique_x) + x_index
    complete = len(cells) == len(unique_x) * len(unique_y) and len(np.unique(cells)) == len(cells)
    if not complete or len(unique_x) < 2 or len(unique_y) < 2:
        return False, "Boundary unavailable: requires a complete, unique x-y grid"
    if not np.any(status == "survived"):
        return False, "No sampled surviving region; no aperture boundary can be drawn"
    if not np.any(status == "lost"):
        return False, "No sampled loss boundary; scan extent is not the DA boundary"

    stable = np.full((len(unique_y), len(unique_x)), np.nan)
    stable[y_index[status == "lost"], x_index[status == "lost"]] = 0.0
    stable[y_index[status == "survived"], x_index[status == "survived"]] = 1.0
    corners = (stable[:-1, :-1], stable[1:, :-1], stable[:-1, 1:], stable[1:, 1:])
    classified = np.logical_and.reduce([np.isfinite(corner) for corner in corners])
    mixed = (np.minimum.reduce(corners) < 0.5) & (np.maximum.reduce(corners) > 0.5)
    if not np.any(classified & mixed):
        return False, "Boundary unavailable: no fully classified cell brackets survival and loss"

    contour = ax.contour(unique_x,
                         unique_y,
                         np.ma.masked_invalid(stable),
                         levels=[0.5],
                         colors=[color],
                         linewidths=1.4,
                         linestyles=linestyle,
                         corner_mask=False)
    contour._pass_da_boundary = True
    contour._pass_da_overlay = overlay
    # Contour sticky bounds otherwise clip particles on the scan edge.
    contour.sticky_edges.x.clear()
    contour.sticky_edges.y.clear()
    ax.autoscale_view()
    line, = ax.plot([], [], color=color, linestyle=linestyle, linewidth=1.4, label=label)
    line._pass_da_boundary = True
    line._pass_da_overlay = overlay
    notes = []
    if np.any(stable[[0, -1], :] == 1.0) or np.any(stable[:, [0, -1]] == 1.0):
        notes.append("Survivors reach the scan edge; the unscanned region is not classified.")
    if np.any(~np.isfinite(stable)):
        notes.append("Unknown states are masked; boundaries may have gaps.")
    return True, "\n".join(notes)


def plot_dynamic_aperture(result, *, dp=None, mode="status", ax=None, boundary=True):
    """Plot initial x-y points for one exact initial dp group; return the Axes.

    ``mode`` is ``status`` or ``loss_turn``. Positions are displayed in mm and
    loss colors use absolute simulation turn. Dashed contours locate sampled
    survived/lost transitions on a complete Cartesian grid at fixed px, py and z.
    They are shown by default and can be hidden with ``boundary=False``. They do
    not replace the samples, close the scan edge, bridge unknown states, or
    suppress islands and holes. No contour is inferred when no fully classified
    cell brackets survival and loss, including all-surviving/all-lost scans.
    """
    import matplotlib.pyplot as plt
    from matplotlib.ticker import MaxNLocator

    if mode not in ("status", "loss_turn"):
        raise ValueError("mode must be 'status' or 'loss_turn'")
    values = np.asarray(result["dp_values"])
    if not len(values):
        raise ValueError("No valid initial coordinates are available for plotting")
    if dp is None:
        dp = float(values[0])
    if not np.any(values == dp):
        raise ValueError("dp must equal an available initial dp group")
    if ax is None:
        _, ax = plt.subplots(figsize=(7, 6), constrained_layout=True)
    initial = np.asarray(result["initial_coordinates"])
    selection = np.asarray(result["initial_valid"]) & (initial[:, 5] == dp)
    x = initial[selection, 0] * 1e3
    y = initial[selection, 2] * 1e3
    status = np.asarray(result["status"])[selection]
    loss = np.asarray(result["lost_turn"])[selection]
    styles = {
        "survived": ("#208654", "o", "Survived"),
        "lost": ("#d4533c", "x", "Lost"),
        "invalid": ("#b13da0", "+", "Numerically invalid"),
        "incomplete": ("#e0a128", "s", "Incomplete coverage"),
        "unavailable": ("#80858a", ".", "Unavailable"),
    }
    for name, (color, marker, label) in styles.items():
        chosen = status == name
        if mode == "loss_turn" and name == "lost":
            chosen &= loss < 0
            label = "Lost (turn unavailable)"
        if np.any(chosen):
            artist = ax.scatter(x[chosen], y[chosen], c=color, marker=marker, s=18, linewidths=0.8, label=label, rasterized=len(x) > 10000)
            artist._pass_particle_ids = np.asarray(result["particle_id"])[selection][chosen]
    if mode == "loss_turn":
        chosen = (status == "lost") & (loss >= 0)
        if np.any(chosen):
            artist = ax.scatter(x[chosen], y[chosen], c=loss[chosen], cmap="viridis", s=20, linewidths=0, rasterized=len(x) > 10000)
            artist._pass_particle_ids = np.asarray(result["particle_id"])[selection][chosen]
            colorbar = ax.figure.colorbar(artist, ax=ax, label="Loss turn (simulation index)")
            colorbar.locator = MaxNLocator(integer=True)
            colorbar.update_ticks()
    note = ""
    if boundary:
        drawn, note = _draw_boundary(ax, x, y, status, initial[selection][:, [1, 3, 4]])
        if drawn:
            note = "Dashed: sampled survival/loss transitions; accuracy is limited by grid spacing." + ("\n" + note if note else "")
    metadata = result.get("metadata", {})
    turn = metadata.get("requested_turn", "?")
    monitor = metadata.get("Monitor", "monitor")
    ax.set_title(f"Initial dp = {dp:.8g}; turn {turn} at {monitor}")
    ax.set_xlabel("Initial x (mm)")
    ax.set_ylabel("Initial y (mm)")
    ax.set_aspect("equal", adjustable="box")
    ax.grid(alpha=0.2)
    if note:
        ax.text(0.0, -0.17, note, transform=ax.transAxes, fontsize=8, va="top", wrap=True)
    handles, _ = ax.get_legend_handles_labels()
    if handles:
        legend = ax.legend(loc="best", fontsize=8)
        for handle in legend.get_lines():
            if handle.get_label() == "Sampled aperture boundary":
                handle._pass_da_boundary = True
    return ax


def plot_dynamic_aperture_boundaries(result, *, dp_values=None, ax=None):
    """Overlay boundaries of selected exact initial-dp groups; return the Axes.

    ``dp_values=None`` selects every group; otherwise pass a nonempty sequence
    of distinct values from ``result["dp_values"]``. Each group retains its
    color and line style when a subset is selected. Only contours are drawn:
    all holes, islands and open components use the same classified Cartesian
    cells as :func:`plot_dynamic_aperture`. Unknown states stay masked. Groups
    without a supported boundary remain identified in the legend and notes.
    """
    import matplotlib.pyplot as plt

    values = np.asarray(result["dp_values"], dtype=float)
    if not len(values):
        raise ValueError("No valid initial coordinates are available for plotting")
    try:
        selected = values if dp_values is None else np.asarray(dp_values, dtype=float)
    except (TypeError, ValueError) as error:
        raise ValueError("dp_values must be a nonempty sequence of available initial dp groups") from error
    if selected.ndim != 1 or not len(selected) or not np.all(np.isfinite(selected)):
        raise ValueError("dp_values must be a nonempty sequence of finite initial dp groups")
    if len(np.unique(selected)) != len(selected):
        raise ValueError("dp_values must not contain duplicate initial dp groups")
    if not np.all(np.isin(selected, values)):
        raise ValueError("dp_values must equal available initial dp groups")
    if ax is None:
        _, ax = plt.subplots(figsize=(7, 6), constrained_layout=True)
    initial = np.asarray(result["initial_coordinates"])
    initial_valid = np.asarray(result["initial_valid"])
    status = np.asarray(result["status"])
    indices = np.flatnonzero(initial_valid)
    indices = indices[np.argsort(initial[indices, 5], kind="stable")]
    sorted_dp = initial[indices, 5]
    labels = [f"{dp:.8g}" for dp in values]
    _, label_indices, label_counts = np.unique(labels, return_inverse=True, return_counts=True)
    for index in np.flatnonzero(label_counts[label_indices] > 1):
        labels[index] = f"{values[index]:.17g}"
    colors = plt.get_cmap("tab10" if len(values) <= 10 else "turbo")
    linestyles = ("-", "--", "-.", ":")
    notes = ["Sampled survival/loss boundaries; accuracy is limited by grid spacing."]
    for dp in selected:
        index = int(np.flatnonzero(values == dp)[0])
        color = colors(index) if len(values) <= 10 else colors(0.1 + 0.8 * index / (len(values) - 1))
        linestyle = linestyles[index % len(linestyles)]
        start = np.searchsorted(sorted_dp, dp, side="left")
        end = np.searchsorted(sorted_dp, dp, side="right")
        selection = indices[start:end]
        x = initial[selection, 0] * 1e3
        y = initial[selection, 2] * 1e3
        # Keep every selected scan extent visible, even if no contour is supported.
        ax.update_datalim(np.column_stack((x, y)))
        label = f"dp0 = {labels[index]}"
        drawn, note = _draw_boundary(ax,
                                     x,
                                     y,
                                     status[selection],
                                     initial[selection][:, [1, 3, 4]],
                                     color=color,
                                     linestyle=linestyle,
                                     label=label,
                                     overlay=True)
        if not drawn:
            line, = ax.plot([], [], color=color, linestyle="none", marker="x", label=label + " (no boundary)")
            line._pass_da_boundary = True
            line._pass_da_overlay = True
        if note:
            note = " ".join(note.splitlines())
            notes.append(f"{label}: {note}")
    metadata = result.get("metadata", {})
    turn = metadata.get("requested_turn", "?")
    monitor = metadata.get("Monitor", "monitor")
    ax.set_title(f"Initial dp boundary comparison; turn {turn} at {monitor}")
    ax.set_xlabel("Initial x (mm)")
    ax.set_ylabel("Initial y (mm)")
    ax.set_aspect("equal", adjustable="box")
    ax.grid(alpha=0.2)
    ax.autoscale_view()
    ax.text(0.0, -0.17, "\n".join(notes), transform=ax.transAxes, fontsize=8, va="top", wrap=True)
    legend = ax.legend(loc="best", fontsize=8)
    for handle in legend.get_lines():
        handle._pass_da_boundary = True
        handle._pass_da_overlay = True
    return ax


# This template is appended to the generated module by export_dynamic_aperture.py.
# Reader, plotting, and export functions are provided by that module.


def main(argv=None):
    """Read a monitor and save a figure, without overwriting existing files."""
    import argparse
    from contextlib import ExitStack
    import shutil
    import tempfile

    parser = argparse.ArgumentParser(description="Plot dynamic aperture from one ParticleMonitor HDF5 or TFS file.")
    parser.add_argument("file", type=Path, help="Current single-file ParticleMonitor output (format version 2).")
    parser.add_argument("--turn", type=int, help="Inclusive simulation turn at this monitor; defaults to its requested final turn.")
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--dp", type=float, help="One exact initial dp group; defaults to the first group.")
    selection.add_argument("--dp-values", type=float, nargs="+", help="Initial dp groups to include with --overlay.")
    parser.add_argument("--overlay", action="store_true", help="Overlay boundaries for all dp groups, or the --dp-values subset.")
    parser.add_argument("--mode", choices=("status", "loss_turn"), default="status", help="Single-dp scatter coloring.")
    parser.add_argument("--output", type=Path, required=True, help="New figure path ending in .png, .pdf or .svg.")
    parser.add_argument("--data", type=Path, help="Optional new .npz or .csv result file; CSV also writes a .json metadata file.")
    args = parser.parse_args(argv)
    if args.turn is not None and args.turn < 0:
        parser.error("--turn must be nonnegative")
    if args.overlay and args.dp is not None:
        parser.error("--dp selects a single plot; use --dp-values with --overlay")
    if args.dp_values is not None and not args.overlay:
        parser.error("--dp-values requires --overlay")
    if args.overlay and args.mode != "status":
        parser.error("--mode loss_turn applies only to a single-dp plot")
    if args.output.suffix.lower() not in {".png", ".pdf", ".svg"}:
        parser.error("--output must end in .png, .pdf or .svg")
    if args.data is not None and args.data.suffix.lower() not in {".npz", ".csv"}:
        parser.error("--data must end in .npz or .csv")
    targets = [args.output]
    if args.data is not None:
        targets.append(args.data)
        if args.data.suffix.lower() == ".csv":
            targets.append(args.data.with_suffix(".json"))
    resolved = [path.resolve() for path in targets]
    if len(set(resolved)) != len(resolved):
        parser.error("Output paths must be distinct")
    for path in targets:
        if path.exists():
            parser.error(f"Refusing to overwrite an existing file: {path}")
        if not path.parent.is_dir():
            parser.error(f"Output directory does not exist: {path.parent}")

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ax = None
    try:
        result = read_dynamic_aperture(args.file, requested_turn=args.turn)
        if args.overlay:
            ax = plot_dynamic_aperture_boundaries(result, dp_values=args.dp_values)
        else:
            ax = plot_dynamic_aperture(result, dp=args.dp, mode=args.mode)
        with tempfile.TemporaryDirectory(prefix="pass_da_") as directory:
            temporary = Path(directory)
            image_path = temporary / ("aperture" + args.output.suffix.lower())
            ax.figure.savefig(image_path, dpi=180)
            products = [image_path]
            if args.data is not None:
                data_path = temporary / ("results" + args.data.suffix.lower())
                export_dynamic_aperture(result, data_path)
                products.append(data_path)
                if args.data.suffix.lower() == ".csv":
                    products.append(data_path.with_suffix(".json"))
            # Exclusive creation also protects files appearing after preflight.
            with ExitStack() as stack:
                streams = [stack.enter_context(path.open("xb")) for path in targets]
                for product, stream in zip(products, streams):
                    with product.open("rb") as source:
                        shutil.copyfileobj(source, stream)
        print(f"Analyzed monitor turn {result['metadata']['requested_turn']}; {len(result['particle_id'])} particles.")
        for path in targets:
            print(path.resolve())
    except (OSError, ValueError, KeyError, ImportError) as error:
        parser.exit(1, f"Dynamic-aperture analysis failed: {error}\n")
    finally:
        if ax is not None:
            plt.close(ax.figure)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
