"""Analyse initial distributions generated by Example 01.

Usage:
    python analyse.py --case transverse
    python analyse.py --case all
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tfs
from scipy.optimize import brentq

from make_input import CASES, selected_cases


SCRIPT_DIR = Path(__file__).resolve().parent


def latest_run_dir(case_name: str) -> Path:
    """Return the most recent output directory for a generated case."""
    root = SCRIPT_DIR / "output" / case_name
    candidates = [
        path for path in root.glob("*/*")
        if path.is_dir() and (path / "distribution").is_dir()
    ]
    if not candidates:
        raise FileNotFoundError(
            f"No completed run found for '{case_name}'. Run "
            f"`python run.py --case {case_name}` first."
        )
    return max(candidates, key=lambda path: path.stat().st_mtime)


def distribution_files(run_dir: Path) -> list[Path]:
    """Return injection-distribution files in bunch order."""
    def bunch_id(path: Path) -> int:
        match = re.search(r"_bunch(\d+)_", path.name)
        return int(match.group(1)) if match else -1

    return sorted((run_dir / "distribution").glob("*_injection.tfs"), key=bunch_id)


def transverse_emittance(x: np.ndarray, px: np.ndarray) -> float:
    """Return RMS geometric emittance from a transverse covariance matrix."""
    x_centered = x - np.mean(x)
    px_centered = px - np.mean(px)
    determinant = (
        np.mean(x_centered**2) * np.mean(px_centered**2)
        - np.mean(x_centered * px_centered) ** 2
    )
    return math.sqrt(max(float(determinant), 0.0))


def transverse_twiss(x: np.ndarray, px: np.ndarray) -> tuple[float, float, float]:
    """Return (emittance, alpha, beta) from centered particle coordinates."""
    x_centered = x - np.mean(x)
    px_centered = px - np.mean(px)
    sigma_x2 = float(np.mean(x_centered**2))
    sigma_px2 = float(np.mean(px_centered**2))
    sigma_xpx = float(np.mean(x_centered * px_centered))
    emit = math.sqrt(max(sigma_x2 * sigma_px2 - sigma_xpx**2, 0.0))
    if emit <= 0.0:
        return emit, 0.0, 0.0
    return emit, -sigma_xpx / emit, sigma_x2 / emit


def relative_error(actual: float, theory: float | None) -> float | None:
    """Return (actual - theory) / theory, or None when no theory is defined."""
    if theory is None or abs(theory) < 1e-30:
        return None
    return (actual - theory) / theory


def rf_bucket_theory(headers) -> dict:
    """Calculate the RF bucket limits using PASS InjectionBunchInfo formulas."""
    kinetic_energy = float(headers["Ek"])
    mass = float(headers["m0"])
    circumference = 2.0 * math.pi * float(headers["Rho"])
    gamma_t = float(headers["Gamma T"])
    harmonic = int(headers["Harmonic num"])
    voltage = float(headers["RF voltage"])
    phase = float(headers["RF phase"])
    charge = float(headers["Charge num"])
    mass_number = int(headers["Proton num"]) + int(headers["Neutron num"])
    qm_ratio = abs(charge) / mass_number

    gamma = 1.0 + kinetic_energy / mass
    beta = math.sqrt(1.0 - 1.0 / gamma**2)
    total_energy = kinetic_energy + mass
    eta = 1.0 / gamma_t**2 - 1.0 / gamma**2
    rho = circumference / (2.0 * math.pi)
    pi = math.pi

    if harmonic <= 0 or abs(voltage) < 1e-30 or abs(eta) < 1e-30:
        return {}

    def separatrix_equation(phi: float) -> float:
        return (
            math.cos(phi)
            + phi * math.sin(phase)
            + math.cos(phase)
            - (pi - phase) * math.sin(phase)
        )

    if eta < 0.0:
        phi_min = brentq(separatrix_equation, -pi, phase)
        phi_max = pi - phase
    else:
        phi_min = pi - phase
        phi_max = brentq(separatrix_equation, phase, 2.0 * pi)

    def z_from_phi(phi: float) -> float:
        return rho * (phase - phi) / harmonic

    z_min = z_from_phi(phi_max)
    z_max = z_from_phi(phi_min)
    dp_temp = (
        -qm_ratio
        * voltage
        / (pi * beta**2 * total_energy * harmonic * eta)
        * (
            2.0 * math.cos(phase)
            - (pi - 2.0 * phase) * math.sin(phase)
        )
    )
    dp_max = math.sqrt(max(dp_temp, 0.0))
    qs_temp = (
        -qm_ratio
        * harmonic
        * voltage
        * eta
        * math.cos(phase)
        / (2.0 * pi * beta**2 * total_energy)
    )
    qs = math.sqrt(max(qs_temp, 0.0))

    return {
        "bucket_z_min": z_min,
        "bucket_z_max": z_max,
        "bucket_dp_max": dp_max,
        "synchrotron_tune": qs,
        "slip_factor": eta,
    }


def summarise(path: Path) -> dict:
    """Read one distribution file and return validation and RMS statistics."""
    df = tfs.read(path)
    values = df[["x", "px", "y", "py", "z", "dp"]].to_numpy(dtype=float)
    if not np.isfinite(values).all():
        raise ValueError(f"Non-finite particle coordinates in {path}")

    headers = df.headers
    emit_x, alpha_x, beta_x = transverse_twiss(
        df["x"].to_numpy(), df["px"].to_numpy()
    )
    emit_y, alpha_y, beta_y = transverse_twiss(
        df["y"].to_numpy(), df["py"].to_numpy()
    )

    alpha_x_theory = float(headers["Alpha x"])
    alpha_y_theory = float(headers["Alpha y"])
    beta_x_theory = float(headers["Beta x"])
    beta_y_theory = float(headers["Beta Y"])
    emit_x_theory = float(headers["Emit x"])
    emit_y_theory = float(headers["Emit y"])
    gamma_x_theory = (1.0 + alpha_x_theory**2) / beta_x_theory
    gamma_y_theory = (1.0 + alpha_y_theory**2) / beta_y_theory
    sigma_x_theory = math.sqrt(beta_x_theory * emit_x_theory)
    sigma_px_theory = math.sqrt(gamma_x_theory * emit_x_theory)
    sigma_y_theory = math.sqrt(beta_y_theory * emit_y_theory)
    sigma_py_theory = math.sqrt(gamma_y_theory * emit_y_theory)

    longitudinal = str(headers["Longi type"]).lower()
    configured_sigma_z = float(headers["Sigma z"])
    configured_sigma_dp = float(headers["Delta p/p"])
    theory_sigma_z = None
    theory_sigma_dp = None
    bucket = {}
    if longitudinal == "gaussian":
        theory_sigma_z = configured_sigma_z
        theory_sigma_dp = configured_sigma_dp
    elif longitudinal == "coasting":
        circumference = 2.0 * math.pi * float(headers["Rho"])
        theory_sigma_z = circumference / math.sqrt(12.0)
        theory_sigma_dp = configured_sigma_dp
    elif longitudinal in {"matchz", "matchdp"}:
        bucket = rf_bucket_theory(headers)
        if longitudinal == "matchdp":
            theory_sigma_dp = configured_sigma_dp

    summary = {
        "file": path.name,
        "transverse": str(headers["Trans type"]),
        "longitudinal": str(headers["Longi type"]),
        "particles": len(df),
        "sigma_x": float(df["x"].std(ddof=0)),
        "sigma_px": float(df["px"].std(ddof=0)),
        "sigma_y": float(df["y"].std(ddof=0)),
        "sigma_py": float(df["py"].std(ddof=0)),
        "sigma_z": float(df["z"].std(ddof=0)),
        "sigma_dp": float(df["dp"].std(ddof=0)),
        "emit_x": emit_x,
        "emit_y": emit_y,
        "alpha_x": alpha_x,
        "alpha_y": alpha_y,
        "beta_x": beta_x,
        "beta_y": beta_y,
        "theory_sigma_x": sigma_x_theory,
        "theory_sigma_px": sigma_px_theory,
        "theory_sigma_y": sigma_y_theory,
        "theory_sigma_py": sigma_py_theory,
        "theory_emit_x": emit_x_theory,
        "theory_emit_y": emit_y_theory,
        "theory_alpha_x": alpha_x_theory,
        "theory_alpha_y": alpha_y_theory,
        "theory_beta_x": beta_x_theory,
        "theory_beta_y": beta_y_theory,
        "theory_sigma_z": theory_sigma_z,
        "theory_sigma_dp": theory_sigma_dp,
        "requested_sigma_z": configured_sigma_z if longitudinal == "matchz" else None,
        "requested_sigma_dp": configured_sigma_dp if longitudinal == "matchdp" else None,
        "sigma_x_rel_error": relative_error(float(df["x"].std(ddof=0)), sigma_x_theory),
        "sigma_px_rel_error": relative_error(float(df["px"].std(ddof=0)), sigma_px_theory),
        "sigma_y_rel_error": relative_error(float(df["y"].std(ddof=0)), sigma_y_theory),
        "sigma_py_rel_error": relative_error(float(df["py"].std(ddof=0)), sigma_py_theory),
        "emit_x_rel_error": relative_error(emit_x, emit_x_theory),
        "emit_y_rel_error": relative_error(emit_y, emit_y_theory),
        "alpha_x_abs_error": alpha_x - alpha_x_theory,
        "alpha_y_abs_error": alpha_y - alpha_y_theory,
        "beta_x_rel_error": relative_error(beta_x, beta_x_theory),
        "beta_y_rel_error": relative_error(beta_y, beta_y_theory),
        "sigma_z_rel_error": relative_error(float(df["z"].std(ddof=0)), theory_sigma_z),
        "sigma_dp_rel_error": relative_error(float(df["dp"].std(ddof=0)), theory_sigma_dp),
        "bucket_z_min": bucket.get("bucket_z_min"),
        "bucket_z_max": bucket.get("bucket_z_max"),
        "bucket_dp_max": bucket.get("bucket_dp_max"),
        "synchrotron_tune": bucket.get("synchrotron_tune"),
        "slip_factor": bucket.get("slip_factor"),
        "configured_sigma_z": configured_sigma_z,
        "configured_sigma_dp": configured_sigma_dp,
        "z_min": float(df["z"].min()),
        "z_max": float(df["z"].max()),
        "dp_min": float(df["dp"].min()),
        "dp_max": float(df["dp"].max()),
    }
    if longitudinal == "matchz" and bucket:
        nearest_bucket_boundary = min(
            abs(bucket["bucket_z_min"]),
            abs(bucket["bucket_z_max"]),
        )
        summary["matchz_bucket_limit_ratio"] = (
            configured_sigma_z / nearest_bucket_boundary
        )
        summary["matchz_requested_4sigma_ratio"] = (
            4.0 * configured_sigma_z / nearest_bucket_boundary
        )
    else:
        summary["matchz_bucket_limit_ratio"] = None
        summary["matchz_requested_4sigma_ratio"] = None
    return summary


def plot_distributions(case_name: str, files: list[Path], analysis_dir: Path) -> Path:
    """Save x-px, y-py, and z-dp scatter plots for every bunch in a case."""
    fig, axes = plt.subplots(
        len(files),
        3,
        figsize=(13, 3.4 * len(files)),
        squeeze=False,
    )

    for bunch_id, path in enumerate(files):
        df = tfs.read(path)
        headers = df.headers
        label = f"bunch{bunch_id}: {headers['Trans type']} / {headers['Longi type']}"
        planes = [
            ("x", "px", "x (m)", "px", "x-px"),
            ("y", "py", "y (m)", "py", "y-py"),
            ("z", "dp", "z (m)", "dp", "z-dp"),
        ]
        for axis, (x_name, y_name, x_label, y_label, title) in zip(axes[bunch_id], planes):
            axis.scatter(
                df[x_name],
                df[y_name],
                s=1.0,
                alpha=0.28,
                linewidths=0,
                rasterized=True,
            )
            axis.set_xlabel(x_label)
            axis.set_ylabel(y_label)
            axis.set_title(f"{label}, {title}")
            axis.grid(alpha=0.25)

    fig.tight_layout()
    plot_path = analysis_dir / f"{case_name}_distributions.png"
    fig.savefig(plot_path, dpi=160)
    plt.close(fig)
    return plot_path


def analyse_case(case_name: str) -> None:
    """Validate files and write a compact summary plus distribution plots."""
    run_dir = latest_run_dir(case_name)
    files = distribution_files(run_dir)
    expected_specs = CASES[case_name]["bunches"]

    if len(files) != len(expected_specs):
        raise ValueError(
            f"{case_name}: expected {len(expected_specs)} saved bunches, found {len(files)}"
        )

    summaries = []
    for bunch_id, (path, expected) in enumerate(zip(files, expected_specs)):
        summary = summarise(path)
        if summary["transverse"] != expected["transverse"]:
            raise ValueError(
                f"{path.name}: expected transverse={expected['transverse']}, "
                f"got {summary['transverse']}"
            )
        if summary["longitudinal"] != expected["longitudinal"]:
            raise ValueError(
                f"{path.name}: expected longitudinal={expected['longitudinal']}, "
                f"got {summary['longitudinal']}"
            )
        summary["bunch"] = bunch_id
        summaries.append(summary)

    analysis_dir = run_dir / "analysis"
    analysis_dir.mkdir(exist_ok=True)
    summary_path = analysis_dir / f"{case_name}_summary.csv"
    pd.DataFrame(summaries).to_csv(summary_path, index=False)
    plot_path = plot_distributions(case_name, files, analysis_dir)

    print(f"[Analyse] {case_name}")
    print(f"  run: {run_dir}")
    print(f"  summary: {summary_path}")
    print(f"  plot: {plot_path}")
    for summary in summaries:
        print(
            f"  bunch{summary['bunch']}: {summary['transverse']}/"
            f"{summary['longitudinal']}, N={summary['particles']}, "
            f"emit_x={summary['emit_x']:.4e} "
            f"(theory {summary['theory_emit_x']:.4e}, "
            f"err {summary['emit_x_rel_error']:+.2%}), "
            f"emit_y={summary['emit_y']:.4e} "
            f"(theory {summary['theory_emit_y']:.4e}, "
            f"err {summary['emit_y_rel_error']:+.2%})"
        )
        if summary["theory_sigma_z"] is not None:
            print(
                f"    sigma_z={summary['sigma_z']:.4e} "
                f"(theory {summary['theory_sigma_z']:.4e}, "
                f"err {summary['sigma_z_rel_error']:+.2%})"
            )
        elif summary["longitudinal"].lower() == "matchz":
            print(
                f"    sigma_z={summary['sigma_z']:.4e} "
                f"(requested {summary['requested_sigma_z']:.4e}; "
                f"requested 4-sigma / nearest bucket boundary="
                f"{summary['matchz_requested_4sigma_ratio']:.3f})"
            )
        if summary["theory_sigma_dp"] is not None:
            print(
                f"    sigma_dp={summary['sigma_dp']:.4e} "
                f"(theory {summary['theory_sigma_dp']:.4e}, "
                f"err {summary['sigma_dp_rel_error']:+.2%})"
            )
        if summary["bucket_dp_max"] is not None:
            print(
                f"    RF theory: z=[{summary['bucket_z_min']:.4e}, "
                f"{summary['bucket_z_max']:.4e}] m, "
                f"dp_max={summary['bucket_dp_max']:.4e}, "
                f"Qs={summary['synchrotron_tune']:.4e}"
            )
            if summary["longitudinal"].lower() == "matchz":
                print(
                    f"    MatchZ requested sigma_z={summary['requested_sigma_z']:.4e}; "
                    f"bucket z span is not large enough for 4 sigma"
                )


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyse Example 01 outputs.")
    parser.add_argument(
        "--case",
        choices=["all", *CASES],
        default="all",
        help="Completed case to analyse (default: all).",
    )
    args = parser.parse_args()

    for case_name in selected_cases(args.case):
        analyse_case(case_name)


if __name__ == "__main__":
    main()
