"""Export PASS's maintained DA reader and plot functions as one portable module.

The exporter needs only the Python standard library. Run it after changing the
source modules, or use --check to verify the committed portable copy is current.
"""

import argparse
import ast
import hashlib
from pathlib import Path


def _build_bundle(root):
    sources = (
        "PASS/utils/particle_monitor_read.py",
        "PASS/analysis/dynamic_aperture.py",
        "PASS/plot/plot_dynamic_aperture.py",
    )
    imports, bindings, sections, hashes = {}, {}, [], []
    bridge = "from PASS.utils.particle_monitor_read import read_particle_monitor_tfs"
    bridge_count = 0
    for relative in sources:
        source = (root / relative).read_text(encoding="utf-8")
        tree = ast.parse(source, filename=relative)
        lines = source.splitlines(keepends=True)
        removed = set()
        hashes.append(f"# {relative}: {hashlib.sha256(source.encode('utf-8')).hexdigest()}")
        for node in ast.walk(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                names = [alias.name for alias in node.names] if isinstance(node, ast.Import) else [node.module or ""]
                project_import = any(name == "PASS" or name.startswith("PASS.") for name in names)
                if project_import or (isinstance(node, ast.ImportFrom) and node.level):
                    statement = ast.get_source_segment(source, node)
                    if relative == "PASS/analysis/dynamic_aperture.py" and statement == bridge:
                        removed.update(range(node.lineno - 1, node.end_lineno))
                        bridge_count += 1
                    else:
                        raise ValueError(f"Unexpected project import in {relative}: {statement}")
        for index, node in enumerate(tree.body):
            if index == 0 and isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
                removed.update(range(node.lineno - 1, node.end_lineno))
                continue
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                statement = ast.get_source_segment(source, node)
                removed.update(range(node.lineno - 1, node.end_lineno))
                if isinstance(node, ast.ImportFrom) and node.module == "__future__":
                    if statement != "from __future__ import annotations":
                        raise ValueError(f"Unexpected future import: {statement}")
                    continue
                imports[statement] = node
                for alias in node.names:
                    name = alias.asname or (alias.name.split(".")[0] if isinstance(node, ast.Import) else alias.name)
                    key = ("import", ast.dump(node, include_attributes=False))
                    if name in bindings and bindings[name] != key:
                        raise ValueError(f"Conflicting top-level name {name} in {relative}")
                    bindings[name] = key
            elif isinstance(node, ast.FunctionDef):
                if node.name in bindings:
                    raise ValueError(f"Conflicting top-level name {node.name} in {relative}")
                bindings[node.name] = ("function", relative)
            else:
                raise ValueError(f"Unsupported top-level statement in {relative}: {type(node).__name__}")
        body = "".join(line for index, line in enumerate(lines) if index not in removed).strip()
        sections.append(f"# Source: {relative}\n\n\n{body}")
    if bridge_count != 1:
        raise ValueError(f"Expected exactly one internal reader import, found {bridge_count}")
    standard, third_party = [], []
    for statement, node in imports.items():
        module = node.names[0].name if isinstance(node, ast.Import) else node.module
        (third_party if module.split(".")[0] == "numpy" else standard).append(statement)
    preamble = ('"""Portable ParticleMonitor dynamic-aperture analysis and plotting.\n\n'
                "Copy this file anywhere; PASS and its GUI are not required.\n"
                "Dependencies: Python >= 3.11, NumPy, h5py, Matplotlib.\n"
                "Generated by tools/export_dynamic_aperture.py; edit the source modules.\n"
                '"""\n\n'
                "from __future__ import annotations\n\n" + "\n".join(sorted(standard)) + "\n\n" + "\n".join(sorted(third_party)) + "\n\n" +
                "\n".join(hashes))
    cli = (root / "tools" / "_dynamic_aperture_cli.py").read_text(encoding="utf-8").strip()
    cli_tree = ast.parse(cli)
    for node in cli_tree.body:
        if isinstance(node, ast.FunctionDef) and node.name in bindings:
            raise ValueError(f"CLI name conflicts with analysis function: {node.name}")
    bundle = preamble + "\n\n" + "\n\n\n".join(sections) + "\n\n\n" + cli + "\n"
    ast.parse(bundle)
    return bundle


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the generated standalone module is absent or out of date.")
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    output = root / "example" / "07_dynamic_aperture" / "standalone" / "dynamic_aperture.py"
    bundle = _build_bundle(root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != bundle:
            parser.exit(1, "Standalone module is out of date; run python tools/export_dynamic_aperture.py\n")
        print("Standalone dynamic-aperture module is current.")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(bundle, encoding="utf-8", newline="\n")
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
