title: PASS
description: Particle Accelerator Simulation Studio

theme: just-the-docs

url: https://changmx.github.io
baseurl: /PASS

logo: assets/logo.png

nav_external_links:
  - title: GitHub
    url: https://github.com/changmx/PASS