title: PASS
description: Particle Accelerator Simulation Studio

url: https://changmx.github.io
baseurl: /PASS

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

logo: assets/logo.png

nav_external_links:
  - title: GitHub
    url: https://github.com/changmx/PASS